import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Tooltip,
  Legend,
} from "chart.js";

import { Bar } from "react-chartjs-2";

import "./WardPerformanceChart.css";

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Tooltip,
  Legend
);

function WardPerformanceChart() {

  const data = {

    labels: [
      "Ward 1",
      "Ward 2",
      "Ward 3",
      "Ward 4",
      "Ward 5",
      "Ward 6",
    ],

    datasets: [

      {

        label: "Waste (kg)",

        data: [480,320,550,290,610,430],

        backgroundColor: "#2563eb",

        borderRadius:8,

      },

    ],

  };

  const options = {

    indexAxis:"y",

    responsive:true,

    maintainAspectRatio:false,

    plugins:{

      legend:{
        display:false,
      },

      title:{

        display:true,

        text:"Ward Performance",

        font:{
          size:18,
          weight:"bold",
        },

        color:"#1e293b",

      },

    },

    scales:{

      x:{

        beginAtZero:true,

        grid:{
          color:"#e5e7eb",
        },

      },

      y:{

        grid:{
          display:false,
        },

      },

    },

  };

  return (

    <div className="ward-chart-card">

      <div className="ward-header">

        <div>

          <h2>🏙 Ward Performance</h2>

          <p>Waste generated by each ward</p>

        </div>

      </div>

      <div className="ward-chart">

        <Bar
          data={data}
          options={options}
        />

      </div>

    </div>

  );

}

export default WardPerformanceChart;