import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

import "./Reports.css";

function Reports() {

    const reports = [

        {
            title: "Daily Waste Report",
            description: "Summary of waste collected across all wards.",
            icon: "🗑️",
            button: "Download PDF"
        },

        {
            title: "AI Prediction Report",
            description: "Overflow predictions generated by the ML model.",
            icon: "🤖",
            button: "Export CSV"
        },

        {
            title: "Economic Impact Report",
            description: "Fuel savings, cost reduction and CO₂ analysis.",
            icon: "💰",
            button: "Download PDF"
        },

        {
            title: "Ward Performance Report",
            description: "Ward-wise efficiency and collection statistics.",
            icon: "📊",
            button: "View Report"
        }

    ];

    return (

        <div className="reports-page">

            <Navbar />

            <div className="dashboard-body">

                <Sidebar />

                <main className="reports-content">

                    <div className="page-header">

                        <h1>📄 Reports Center</h1>

                        <p>
                            Generate, export and monitor all smart city reports from one place.
                        </p>

                    </div>

                    <div className="reports-grid">

                        {reports.map((report, index) => (

                            <div
                                key={index}
                                className="report-card"
                            >

                                <div className="report-icon">
                                    {report.icon}
                                </div>

                                <h3>{report.title}</h3>

                                <p>{report.description}</p>

                                <button>
                                    {report.button}
                                </button>

                            </div>

                        ))}

                    </div>

                </main>

            </div>

        </div>

    );

}

export default Reports;